CREATE DATABASE SSIS_TEST; --QUERY TO CREATE DATABASE
USE SSIS_TEST; --QUERY TO CHANGE TO NEW DATABASE CREATED

CREATE TABLE USERS_TEST(USERNAME VARCHAR(10), CONTROL_NUMBER VARCHAR(10), MAIL VARCHAR(50), ROL VARCHAR(15), 
	CONSTRAINT PK_USER_TEST PRIMARY KEY(USERNAME)); --QUERY TO CREATE TABLE "USER_TEST"

SELECT * FROM USERS_TEST; --QUERY TO CHECK DATA IN TABLE "USER_TEST"

DELETE FROM USERS_TEST; --QUERY TO CLEAN DATA IN USERS_TEST